### ISSUE TITLE
How can i use Pychips? 

### ISSUE THREAD

**Issue by ashkan1375** [lnxpy/pychips#1]
Hi Alireza 😉
I saw Pychips Repo in You'r Archive..
And i enjoyed your project to 'HOW TO MAKE MY OWN PICTURE'..

But Now I've a bad problem.. 
How can i use Pychips?

**Comment by frowzyispenguin** [comment]
### a guide for how to use "pychips" ### 

go to the page of "pychips" 
watch the gif .. everythin' is crystal clear :smile:

**Comment by lnxpy** [comment]
Hi mr.sedaghat ❤️
This Qt is so easy to answer.. 
> how to use Pychips?
You can use usage.gif.. 
you can find it in : https://github.com/lnxpy/Pychips/blob/master/README.md

Have Fun ❤️😊
